# Generated by Django 3.2.4 on 2021-06-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countingunit',
            name='unit',
            field=models.CharField(max_length=50),
        ),
    ]
