# Generated by Django 3.2.4 on 2021-06-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_transactions_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='countingUnit',
        ),
        migrations.RemoveField(
            model_name='products',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='products',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='transactions',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
