# Generated by Django 3.2.4 on 2021-06-28 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210604_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transactions'),
        ),
    ]
