# Generated by Django 3.2.4 on 2021-07-12 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_orderdetails_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='customerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer'),
        ),
    ]
