# Generated by Django 3.2.3 on 2021-05-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_black', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminblacksetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
