# Generated by Django 2.2.13 on 2022-08-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_black', '0002_alter_adminblacksetting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminblacksetting',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
